python inference_video.py --model-type mattingbase \
        --model-backbone mobilenetv2 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "/home/bxg/data/bg2/pytorch_mobilenetv2.pth" \
        --video-src "/home/bxg/data/bg2/bxg2.mp4" \
        --video-bgr "/home/bxg/data/bg2/bxg2.png" \
        --output-dir "/home/bxg/data/bg2/output/" \
        --device cpu \
        --output-type com
