python inference_video.py --model-type mattingrefine \
        --model-backbone resnet50 \
        --model-backbone-scale 0.25 \
        --model-refine-mode thresholding \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "/mnt/data/matting/pretrain/pytorch_resnet50.pth" \
        --video-src "/mnt/work/home/bxg/input/bxg.mp4" \
        --video-bgr "/mnt/work/home/bxg/input/bxg.png" \
        --output-dir "/mnt/work/home/bxg/output/resnet50_bxg/" \
        --device cuda \
        --output-type com pha fgr
